 CREATE DATABASE HOSPITAL;
 USE HOSPITAL;

 -- PATIENT table
 CREATE TABLE PATIENT (
     PATIENT_ID NUMBER PRIMARY KEY,
     NAME VARCHAR2(100) NOT NULL,
     DOB DATE,
     GENDER VARCHAR2(10)
 );
 
 CREATE SEQUENCE PATIENT_SEQ START WITH 1 INCREMENT BY 1;
 
 CREATE OR REPLACE TRIGGER patient_bi
 BEFORE INSERT ON patient
 FOR EACH ROW
 BEGIN
   SELECT patient_seq.NEXTVAL INTO :NEW.patient_id FROM dual;
 END;
 /

 -- DEPARTMENT table
  CREATE TABLE DEPARTMENT (
     DEPARTMENT_ID NUMBER PRIMARY KEY,
     NAME VARCHAR2(100) NOT NULL
 );

 CREATE SEQUENCE DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER DEPARTMENT_BI
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    :NEW.DEPARTMENT_ID := DEPARTMENT_SEQ.NEXTVAL;
END;
/

-- DOCTOR table
CREATE TABLE DOCTOR (
    DOCTOR_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    SPECIALITY VARCHAR2(50),
    DEPARTMENT_ID NUMBER,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

 CREATE SEQUENCE DOCTOR_SEQ START WITH 1 INCREMENT BY 1;

  CREATE OR REPLACE TRIGGER DOCTOR_BI
 BEFORE INSERT ON DOCTOR
 FOR EACH ROW
 BEGIN
     SELECT DOCTOR_SEQ.NEXTVAL INTO :NEW.DOCTOR_ID FROM dual;
 END;
 /

 -- APPOINTMENT table
 CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER,
    DOCTOR_ID NUMBER,
    APPOINTMENT_DATE DATE,
    DIAGNOSIS VARCHAR2(255),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

CREATE SEQUENCE APPOINTMENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER APPOINTMENT_BI
BEFORE INSERT ON APPOINTMENT
FOR EACH ROW
BEGIN
    SELECT APPOINTMENT_SEQ.NEXTVAL INTO :NEW.APPOINTMENT_ID FROM dual;
END;
/

INSERT ALL
    INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES (PATIENT_SEQ.NEXTVAL, 'John Doe', TO_DATE('1985-05-20', 'YYYY-MM-DD'), 'Male')
    INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES (PATIENT_SEQ.NEXTVAL, 'Jane Smith', TO_DATE('1990-04-15', 'YYYY-MM-DD'), 'Female')
    INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES (PATIENT_SEQ.NEXTVAL, 'Alice Johnson', TO_DATE('1982-12-02', 'YYYY-MM-DD'), 'Female')

SELECT * FROM PATIENT;

INSERT ALL
    INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Cardiology')
    INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Neurology')
    INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Oncology')

SELECT * FROM DEPARTMENT;

INSERT ALL
    INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES (DOCTOR_SEQ.NEXTVAL, 'Dr. Smith', 'Cardiologist', 1)
    INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES (DOCTOR_SEQ.NEXTVAL, 'Dr. Brown', 'Neurologist', 2)
    INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES (DOCTOR_SEQ.NEXTVAL, 'Dr. Clark', 'Oncologist', 3)

SELECT * FROM DOCTOR;

INSERT ALL
  INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS)
    VALUES (APPOINTMENT_SEQ.NEXTVAL, 2, 2, TO_DATE('2025-08-05', 'YYYY-MM-DD'), 'Checkup')
  INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS)
    VALUES (APPOINTMENT_SEQ.NEXTVAL, 3, 3, TO_DATE('2025-08-06', 'YYYY-MM-DD'), 'MRI Scan')
  INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS)
    VALUES (APPOINTMENT_SEQ.NEXTVAL, 4, 4, TO_DATE('2025-08-07', 'YYYY-MM-DD'), 'Radiation Therapy')

SELECT * FROM APPOINTMENT;

-- ALTER
ALTER TABLE PATIENT ADD (EMAIL VARCHAR2(100));
ALTER TABLE DOCTOR DROP COLUMN SPECIALITY;
ALTER TABLE DEPARTMENT ADD (LOCATION VARCHAR2(100));
SELECT * FROM PATIENT;
SELECT * FROM DOCTOR;
SELECT * FROM DEPARTMENT;

--DROP
ALTER TABLE PATIENT DROP COLUMN GENDER;

--TRUNCATE
TRUNCATE TABLE APPOINTMENT;


