CREATE TABLE PATIENT (
    PATIENT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    GENDER VARCHAR(10)
);

-- DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

-- DOCTOR table
CREATE TABLE DOCTOR (
    DOCTOR_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SPECIALITY VARCHAR(50),
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

-- APPOINTMENT table
CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID INT PRIMARY KEY,
    PATIENT_ID INT,
    DOCTOR_ID INT,
    APPOINTMENT_DATE DATE,
    DIAGNOSIS VARCHAR(255),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

-- INSERT into PATIENT
INSERT ALL
  INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES (1, 'John Doe', TO_DATE('1985-05-20', 'YYYY-MM-DD'), 'Male'),
  INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES (2, 'Jane Smith', TO_DATE('1990-04-15', 'YYYY-MM-DD'), 'Female'),
  INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES (3, 'Alice Johnson', TO_DATE('1982-12-02', 'YYYY-MM-DD'), 'Female');



-- INSERT into DEPARTMENT
INSERT ALL
  INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES (1, 'Cardiology'),
  INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES (2, 'Neurology'),
  INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES (3, 'Oncology');


-- INSERT into DOCTOR
INSERT ALL
  INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES (1, 'Dr. Smith', 'Cardiologist', 1),
  INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES (2, 'Dr. Brown', 'Neurologist', 2),
  INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES (3, 'Dr. Clark', 'Oncologist', 3);


-- INSERT into APPOINTMENT
INSERT ALL
  INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS)
      VALUES (1, 2, 2, TO_DATE('2025-08-05', 'YYYY-MM-DD'), 'Checkup'),
  INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS)
      VALUES (2, 3, 3, TO_DATE('2025-08-06', 'YYYY-MM-DD'), 'MRI Scan'),
  INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS)
      VALUES (3, 1, 1, TO_DATE('2025-08-07', 'YYYY-MM-DD'), 'Radiation Therapy');


SELECT * FROM PATIENT;
SELECT * FROM DOCTOR;
SELECT * FROM DEPARTMENT;
SELECT * FROM APPOINTMENT;
