CREATE TABLE PATIENT (
    PATIENT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    GENDER VARCHAR(10)
);

-- DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

-- DOCTOR table
CREATE TABLE DOCTOR (
    DOCTOR_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SPECIALITY VARCHAR(50),
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

-- APPOINTMENT table
CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID INT PRIMARY KEY,
    PATIENT_ID INT,
    DOCTOR_ID INT,
    APPOINTMENT_DATE DATE,
    DIAGNOSIS VARCHAR(255),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

-- INSERT into PATIENT
INSERT INTO PATIENT (PATIENT_ID, NAME, DOB, GENDER) VALUES
    (1, 'John Doe', '1985-05-20', 'Male'),
    (2, 'Jane Smith', '1990-04-15', 'Female'),
    (3, 'Alice Johnson', '1982-12-02', 'Female');

-- INSERT into DEPARTMENT
INSERT INTO DEPARTMENT (DEPARTMENT_ID, NAME) VALUES
    (1, 'Cardiology'),
    (2, 'Neurology'),
    (3, 'Oncology');

-- INSERT into DOCTOR
INSERT INTO DOCTOR (DOCTOR_ID, NAME, SPECIALITY, DEPARTMENT_ID) VALUES
    (1, 'Dr. Smith', 'Cardiologist', 1),
    (2, 'Dr. Brown', 'Neurologist', 2),
    (3, 'Dr. Clark', 'Oncologist', 3);

-- INSERT into APPOINTMENT
INSERT INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, DIAGNOSIS) VALUES
    (1, 2, 2, '2025-08-05', 'Checkup'),
    (2, 3, 3, '2025-08-06', 'MRI Scan'),
    (3, 1, 1, '2025-08-07', 'Radiation Therapy');

SELECT * FROM PATIENT;
SELECT * FROM DOCTOR;
SELECT * FROM DEPARTMENT;
